### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by markmbaum** [oneironautics/shapefile#2]
Have you thought about making this code open source? I have a small, academic application in mind and would incorporate your code with permission.

**Comment by oneironautics** [comment]
Hey! It’s actually MIT licensed already - refer to the inline license in the source files. I can add an MIT license to the repo to avoid confusion. 

Glad you find it useful! I wouldn’t mind hearing more about any applications you use it in.

**Comment by markmbaum** [comment]
Oh, I didn't realize! Thanks. I'm using it to read Polyline files containing river segments and group them into river networks, spitting out some text files with the groupings and intersection points. Then, I'm working on some analysis similar to what's in [this paper](https://arxiv.org/ftp/arxiv/papers/1709/1709.09834.pdf).
